apiVersion: v1
items:
- apiVersion: ocs.openshift.io/v1
  kind: StorageCluster
  metadata:
    annotations:
      uninstall.ocs.openshift.io/cleanup-policy: delete
      uninstall.ocs.openshift.io/mode: graceful
    finalizers:
    - storagecluster.ocs.openshift.io
    name: ocs-storagecluster
    namespace: openshift-storage
  spec:
    arbiter: {}
    encryption:
      enable: true
      kms:
        enable: true
    externalStorage: {}
    flexibleScaling: true
    managedResources:
      cephBlockPools: {}
      cephFilesystems: {}
      cephObjectStoreUsers: {}
      cephObjectStores: {}
    nodeTopologies: {}
    storageDeviceSets:
    - config: {}
      count: 3
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Ti
          storageClassName: thin
          volumeMode: Block
        status: {}
      name: ocs-deviceset-thin
      placement: {}
      preparePlacement: {}
      replica: 1
      resources: {}
    version: 4.7.0
  status:
    failureDomain: host
    nodeTopologies:
      labels:
        kubernetes.io/hostname:
        - compute-0
        - compute-1
        - compute-2
    relatedObjects:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: ocs-storagecluster-cephcluster
      namespace: openshift-storage
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
